const TypeActions = {
	ACCOUNT_LOGIN_REQUEST: "ACCOUNT_LOGIN_REQUEST",
	ACCOUNT_LOGIN_SUCCESS: "ACCOUNT_LOGIN_SUCCESS",
	ACCOUNT_LOGIN_FAILED: "ACCOUNT_LOGIN_FAILED",

	ACCOUNT_FORGOT_PASSWORD_REQUEST: "ACCOUNT_FORGOT_PASSWORD_REQUEST",
	ACCOUNT_FORGOT_PASSWORD_SUCCESS: "ACCOUNT_FORGOT_PASSWORD_SUCCESS",
	ACCOUNT_FORGOT_PASSWORD_FAILED: "ACCOUNT_FORGOT_PASSWORD_FAILED",

	ACCOUNT_RESET_PASSWORD_REQUEST: "ACCOUNT_RESET_PASSWORD_REQUEST",
	ACCOUNT_RESET_PASSWORD_SUCCESS: "ACCOUNT_RESET_PASSWORD_SUCCESS",
	ACCOUNT_RESET_PASSWORD_FAILED: "ACCOUNT_RESET_PASSWORD_FAILED",

	ACCOUNT_LOGOUT_REQUEST: "ACCOUNT_LOGOUT_REQUEST",
	ACCOUNT_LOGOUT_SUCCESS: "ACCOUNT_LOGOUT_SUCCESS",
	ACCOUNT_LOGOUT_FAILED: "ACCOUNT_LOGOUT_FAILED",

	GET_CURRENT_ACCOUNT_REQUEST: "GET_CURRENT_ACCOUNT_REQUEST",
	GET_CURRENT_ACCOUNT_SUCCESS: "GET_CURRENT_ACCOUNT_SUCCESS",
	GET_CURRENT_ACCOUNT_FAILED: "GET_CURRENT_ACCOUNT_FAILED",

	GET_ACCOUNTS_REQUEST: "GET_ACCOUNTS_REQUEST",
	GET_ACCOUNTS_SUCCESS: "GET_ACCOUNTS_SUCCESS",
	GET_ACCOUNTS_FAILED: "GET_ACCOUNTS_FAILED",

	GET_ACCOUNT_BY_ID_REQUEST: "GET_ACCOUNT_BY_ID_REQUEST",
	GET_ACCOUNT_BY_ID_SUCCESS: "GET_ACCOUNT_BY_ID_SUCCESS",
	GET_ACCOUNT_BY_ID_FAILED: "GET_ACCOUNT_BY_ID_FAILED",

	CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
	CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
	CREATE_ACCOUNT_FAILED: "CREATE_ACCOUNT_FAILED",

	UPDATE_ACCOUNT_REQUEST: "UPDATE_ACCOUNT_REQUEST",
	UPDATE_ACCOUNT_SUCCESS: "UPDATE_ACCOUNT_SUCCESS",
	UPDATE_ACCOUNT_FAILED: "UPDATE_ACCOUNT_FAILED",

	DELETE_ACCOUNT_REQUEST: "DELETE_ACCOUNT_REQUEST",
	DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
	DELETE_ACCOUNT_FAILED: "DELETE_ACCOUNT_FAILED",

	//Category
	GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
	GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
	GET_CATEGORIES_FAILED: "GET_CATEGORIES_FAILED",

	CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
	CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
	CREATE_CATEGORY_FAILED: "CREATE_CATEGORY_FAILED",

	UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
	UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
	UPDATE_CATEGORY_FAILED: "UPDATE_CATEGORY_FAILED",

	DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
	DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
	DELETE_CATEGORY_FAILED: "DELETE_CATEGORY_FAILED",

	//Brand
	GET_BRANDS_REQUEST: "GET_BRANDS_REQUEST",
	GET_BRANDS_SUCCESS: "GET_BRANDS_SUCCESS",
	GET_BRANDS_FAILED: "GET_BRANDS_FAILED",

	CREATE_BRAND_REQUEST: "CREATE_BRAND_REQUEST",
	CREATE_BRAND_SUCCESS: "CREATE_BRAND_SUCCESS",
	CREATE_BRAND_FAILED: "CREATE_BRAND_FAILED",

	UPDATE_BRAND_REQUEST: "UPDATE_BRAND_REQUEST",
	UPDATE_BRAND_SUCCESS: "UPDATE_BRAND_SUCCESS",
	UPDATE_BRAND_FAILED: "UPDATE_BRAND_FAILED",

	DELETE_BRAND_REQUEST: "DELETE_BRAND_REQUEST",
	DELETE_BRAND_SUCCESS: "DELETE_BRAND_SUCCESS",
	DELETE_BRAND_FAILED: "DELETE_BRAND_FAILED",

	//Product
	GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
	GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
	GET_PRODUCTS_FAILED: "GET_PRODUCTS_FAILED",

	GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
	GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
	GET_PRODUCT_BY_ID_FAILED: "GET_PRODUCT_BY_ID_FAILED",

	CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
	CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
	CREATE_PRODUCT_FAILED: "CREATE_PRODUCT_FAILED",

	UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
	UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
	UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",

	DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
	DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
	DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",

	//Quản lý phân quyền
	GET_ROLES_REQUEST: "GET_ROLES_REQUEST",
	GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
	GET_ROLES_FAILED: "GET_ROLES_FAILED",

	GET_ROLE_BY_ID_REQUEST: "GET_ROLE_BY_ID_REQUEST",
	GET_ROLE_BY_ID_SUCCESS: "GET_ROLE_BY_ID_SUCCESS",
	GET_ROLE_BY_ID_FAILED: "GET_ROLE_BY_ID_FAILED",

	CREATE_ROLE_REQUEST: "CREATE_ROLE_REQUEST",
	CREATE_ROLE_SUCCESS: "CREATE_ROLE_SUCCESS",
	CREATE_ROLE_FAILED: "CREATE_ROLE_FAILED",

	UPDATE_ROLE_REQUEST: "UPDATE_ROLE_REQUEST",
	UPDATE_ROLE_SUCCESS: "UPDATE_ROLE_SUCCESS",
	UPDATE_ROLE_FAILED: "UPDATE_ROLE_FAILED",

	DELETE_ROLE_REQUEST: "DELETE_ROLE_REQUEST",
	DELETE_ROLE_SUCCESS: "DELETE_ROLE_SUCCESS",
	DELETE_ROLE_FAILED: "DELETE_ROLE_FAILED",

	//Order
	GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
	GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
	GET_ORDERS_FAILED: "GET_ORDERS_FAILED",

	GET_ORDER_BY_ID_REQUEST: "GET_ORDER_BY_ID_REQUEST",
	GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
	GET_ORDER_BY_ID_FAILED: "GET_ORDER_BY_ID_FAILED",

	CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
	CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
	CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED",

	UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
	UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
	UPDATE_ORDER_FAILED: "UPDATE_ORDER_FAILED",

	DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
	DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
	DELETE_ORDER_FAILED: "DELETE_ORDER_FAILED",
};
export default TypeActions;
